#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ..

SUBDIRS = atwork_pb_msgs atwork_device_pb_msgs rcll_pb_msgs 

include $(BASEDIR)/etc/buildsys/config.mk
include $(BUILDSYSDIR)/base.mk
